language: csharp
install:
  - sudo apt-get install nunit-console
  - nuget restore ./EasyConfig.sln

script:
  - xbuild ./EasyConfig.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5 /toolsversion:12.0
  - nunit-console ./EasyConfig.UnitTests/EasyConfig.UnitTests/bin/Release/EasyConfig.UnitTests.dll